### ISSUE TITLE
Error with Dickinson Law IDEAS importer

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#591] opened 2022-11-01 16:58 UTC
Hi Alex -- Sorry that I keep logging bugs. Another one has come up.

Bob Rains (rer10) at Dickinson got an automated email yesterday asking him to deposit about 30 articles. I've spot-checked quite a few, and all the publication records appear to have been imported from the Dickinson Law IDEAS repository. That means they are also openly available there, but somehow we don't have the open access links. (Is it possible they were removed when we removed ScholarSphere links manually during development?) I'm wondering if this impacts others at Dickinson and perhaps the Penn State Law repository as well.

Exacerbating the situation is the fact that the publication date for all but one of his articles is 2020. (There's one from 2007.) I strongly suspect most of these are actually from earlier years and thus not subject to the OA policy, but somehow we're getting 2020 as the publication date. If this is a separate issue, it would certainly be lower priority to fix.

**Comment by ajkiessl** [comment] 2022-11-01 18:39
@anaelizabethenriquez I don't think this was caused by the ScholarSphere links stuff, I believe it's more related to this issue: https://github.com/psu-libraries/researcher-metadata/issues/259 , but I think even that issue isn't necessarily what's causing this problem.  In #259 we added a migration script that should have converted the old open_access_url fields to an OpenAccessLocation record for publications imported from Dickinson/PSU Law.  The source would have been wrong (OAB instead of Dickinson/PSU Law), but these records should at least have OpenAccessLocations from that migration.  The only thing I can come up with as to why they don't have OALs is if I look way back in our commit history, it looks like when we first built the D/PSU Law importer there was some uncertainty about which url field fro them was the proper open access url to use.  I suppose there's the chance before we got that right that some of the records we imported never got an open access url (this is an assumption since I was not a part of this development).  There's also the chance that the field we pull this url from is just blank in D/PSU Law's repository.

The solution to this would be to run the D/PSU Law import again with a slight tweak to the importer to allow OALs to be imported for existing Dickinson/PSU Law publications.  We could also then tell if the url field we get from them is giving us good data.  I can work on a fix for this now.

As for the publication dates, we are grabbing a date from a date field we get from them.  This could be the wrong field.  I'd have to dig into the Law data a little more to figure this out.  I would consider this a separate issue and maybe something we can handle at a later time.

**Closed** 2022-11-02 15:42 UTC
Labels: bug

**Comment by ajkiessl** [comment] 2022-11-02 16:30
@anaelizabethenriquez This is complete and deployed to production.  I ran the importer and it looks like it updated rer10's records to have OpenAccessLocations.  The import also added a handful of new records.  I think it's been a while since we last ran this import.

**Comment by anaelizabethenriquez** [comment] 2022-11-03 14:10
Thanks. Looks good! I have responded to the user's support ticket.
